# Al Hekma Hospital — Phase 1D Healthcare Service Unit creation
# Source authority:
#   AlHekma_ERPNext_Master_Tree_EN.xmind.md  (master)
#   docs/ALHEKMA_SERVICE_UNIT_BLUEPRINT.md   (Section 03 derivative)
#
# bench --site alhekma.local execute alhekma.setup.create_hsu_phase1d.run
#
# Rules applied
# -------------
# - Canonical display names from the Blueprint, verbatim.
# - ERPNext name is auto-generated by autoname(): display_name + " - hikma"
# - Parent references use the auto-generated ERPNext name (with " - hikma").
# - is_group=1 for Area/group nodes; is_group=0 for leaf rooms/beds.
# - allow_appointments: set per unit via flags.allow_appointments_override=True
#     so the AlHekmaHealthcareServiceUnit override preserves the intended value.
#     Only General Practitioner Clinic gets allow_appointments=1.
# - inpatient_occupancy: NOT set here; inherited from Type via standard logic.
#     Bed type has inpatient_occupancy=1, so all Bed leaves get it automatically.
# - company = "alhikma_hospital" on every record.
# - warehouse: left blank (all [D] per blueprint).
# - service_unit_capacity: left blank (all [D] or cleared by group logic).
# - Idempotent: skips any unit whose auto-generated name already exists.
#
# Units NOT created (unresolved [D] or excluded by architecture)
# --------------------------------------------------------------
# - Examination and Treatment Rooms  [D]
# - Observation Area                 [D]
# - Specialty Clinic Rooms           [F]
# - ICU Beds                         [D]
# - Stroke Beds                      [D]
# - Standard Rooms                   [D]
# - Inpatient Beds                   [D]
# - Preoperative Area                [D]
# - External Laboratory              [X] — Supplier, not HSU
# - Ambulance Vehicles               [X] — Assets, not HSU
# - CSSD                             [X] — not a patient-care HSU
# - MRI                              [F] — not currently available


import frappe

COMPANY = "alhikma_hospital"
ABBR = "hikma"


def _n(display_name):
    """Return the ERPNext auto-generated name for a given display name."""
    return f"{display_name} - {ABBR}"


# Definition table
# (display_name, parent_display_name, service_unit_type, is_group, allow_appointments)
#
# allow_appointments is the INTENDED per-unit value.
# For group nodes it is irrelevant (cleared by validate).
# For leaf nodes it is preserved by the AlHekmaHealthcareServiceUnit override.
#
# inpatient_occupancy is NOT listed here — it is inherited from the Type:
#   Bed  -> inpatient_occupancy=1
#   Room -> inpatient_occupancy=0
#   Area -> inpatient_occupancy=0 (and cleared for groups anyway)

UNITS = [
    # ── Level 1: facility root ───────────────────────────────────────────────
    # Parent is the pre-existing root; its name already has the suffix.
    (
        "Al Hekma Hospital - Mansoura",
        "All Healthcare Service Units - hikma",   # pre-existing root, exact name
        "Area", 1, 0,
    ),
    # ── Level 2: service area groups ────────────────────────────────────────
    ("Emergency Department",              "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    ("Outpatient Clinics",                "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    ("Critical Care and Stroke Services", "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    ("Inpatient Services",                "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    ("Operating Theatre Complex",         "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    ("Radiology",                         "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    ("Pharmacy",                          "Al Hekma Hospital - Mansoura", "Area", 1, 0),
    # ── Level 3: Emergency ───────────────────────────────────────────────────
    ("Triage",                           "Emergency Department",              "Room", 0, 0),
    # ── Level 3: Outpatient ─────────────────────────────────────────────────
    ("General Practitioner Clinic",      "Outpatient Clinics",                "Room", 0, 1),  # allow_appointments=1
    # ── Level 3: Critical Care group nodes (individual beds are [D]) ────────
    ("Intensive Care Unit",              "Critical Care and Stroke Services", "Bed",  1, 0),
    ("Stroke Unit",                      "Critical Care and Stroke Services", "Bed",  1, 0),
    # ── Level 3: Inpatient VIP group ────────────────────────────────────────
    ("VIP Rooms",                        "Inpatient Services",                "Room", 1, 0),
    # ── Level 3: Operating Theatre ──────────────────────────────────────────
    ("OR-01",                            "Operating Theatre Complex",         "Room", 0, 0),
    ("OR-02",                            "Operating Theatre Complex",         "Room", 0, 0),
    ("OR-03",                            "Operating Theatre Complex",         "Room", 0, 0),
    ("Post-Anesthesia Care Unit - PACU", "Operating Theatre Complex",         "Bed",  0, 0),
    # ── Level 3: Radiology ──────────────────────────────────────────────────
    ("Computed Tomography Unit - CT",    "Radiology",                         "Room", 0, 0),
    ("Ultrasound Unit",                  "Radiology",                         "Room", 0, 0),
    # ── Level 3: Pharmacy ───────────────────────────────────────────────────
    ("Patient Dispensing Point",         "Pharmacy",                          "Room", 0, 0),
    # ── Level 4: VIP individual rooms ───────────────────────────────────────
    ("VIP-01",                           "VIP Rooms",                         "Room", 0, 0),
    ("VIP-02",                           "VIP Rooms",                         "Room", 0, 0),
    ("VIP-03",                           "VIP Rooms",                         "Room", 0, 0),
    ("VIP-04",                           "VIP Rooms",                         "Room", 0, 0),
    ("VIP-05",                           "VIP Rooms",                         "Room", 0, 0),
]


def run():
    created = []
    skipped = []
    errors  = []

    for (display_name, parent_display_name, unit_type, is_group, allow_appt) in UNITS:
        # Compute the ERPNext name that autoname() will produce
        expected_name = _n(display_name)

        # Compute the parent's ERPNext name.
        # The pre-existing root already carries its full name; all others get suffix.
        if parent_display_name == "All Healthcare Service Units - hikma":
            parent_name = parent_display_name          # pre-existing, no double suffix
        else:
            parent_name = _n(parent_display_name)

        try:
            # Idempotency check
            if frappe.db.exists("Healthcare Service Unit", expected_name):
                skipped.append(expected_name)
                continue

            doc = frappe.new_doc("Healthcare Service Unit")
            doc.healthcare_service_unit_name   = display_name
            doc.parent_healthcare_service_unit = parent_name
            doc.service_unit_type              = unit_type
            doc.is_group                       = is_group
            doc.allow_appointments             = allow_appt
            doc.company                        = COMPANY

            # Activate the per-unit allow_appointments override for leaf nodes.
            # The AlHekmaHealthcareServiceUnit.set_service_unit_properties()
            # will preserve doc.allow_appointments instead of overwriting it
            # from the Type.  For group nodes this flag is irrelevant.
            if not is_group:
                doc.flags.allow_appointments_override = True

            doc.insert(ignore_permissions=True)
            frappe.db.commit()
            created.append(expected_name)

        except Exception as exc:
            frappe.db.rollback()
            errors.append((expected_name, str(exc)))

    print("=== Phase 1D HSU Creation Result ===")
    print(f"Created  ({len(created)}):")
    for n in created:
        print(f"  {n}")
    print(f"Skipped  ({len(skipped)}):")
    for n in skipped:
        print(f"  {n}")
    print(f"Errors   ({len(errors)}):")
    for n, e in errors:
        print(f"  {n}: {e}")

    return {"created": created, "skipped": skipped, "errors": errors}
